#!/usr/bin/env bash
set -euo pipefail

# Load variables from install.conf
source /root/install.conf
uuid=$(blkid -s UUID -o value "$part2")

# --- Set hostname ---
echo "$hostname" >/etc/hostname
echo "127.0.0.1  localhost" >/etc/hosts
echo "::1        localhost" >>/etc/hosts
echo "127.0.1.1  $hostname.localdomain  $hostname" >>/etc/hosts

# Local Setup
ln -sf "/usr/share/zoneinfo/$timezone" /etc/localtime
hwclock --systohc
sed -i 's/^#en_US.UTF-8/en_US.UTF-8/g' /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" >/etc/locale.conf

# Sudo Configuration
echo "%wheel ALL=(ALL) ALL" >/etc/sudoers.d/wheel
echo "Defaults timestamp_timeout=-1" >/etc/sudoers.d/timestamp
# echo "Defaults pwfeedback" >/etc/sudoers.d/pwfeedback
chmod 440 /etc/sudoers.d/*

# Tlp setup
# Robust detection: prefer explicit pstate driver dirs if present, fallback to scaling_driver text
scaling_f="/sys/devices/system/cpu/cpu0/cpufreq/scaling_driver"
pstate_supported=false
driver=""
if [ -d /sys/devices/system/cpu/intel_pstate ]; then
  driver="intel_pstate"
  pstate_supported=true
elif [ -d /sys/devices/system/cpu/amd_pstate ] || [ -d /sys/devices/system/cpu/amd-pstate ]; then
  # kernel docs and kernels may expose amd_pstate/amd-pstate; accept either
  driver="amd_pstate"
  pstate_supported=true
elif [ -r "$scaling_f" ]; then
  # fallback: read scaling_driver and normalise
  rawdrv=$(cat "$scaling_f" 2>/dev/null || true)
  case "$rawdrv" in
  *intel* | intel_pstate | intel-pstate)
    driver="intel_pstate"
    pstate_supported=true
    ;;
  *amd* | amd_pstate | amd-pstate)
    driver="amd_pstate"
    pstate_supported=true
    ;;
  *) driver="$rawdrv" ;;
  esac
fi

# Kernel parameter to encourage pstate driver mode on next boot (set only when pstate is supported)
pstate_param=""
if [ "$pstate_supported" = true ]; then
  if [ "$driver" = "intel_pstate" ]; then
    # prefer 'active' for AC; we'll keep TLP switching to 'passive' on BAT to allow schedutil there.
    pstate_param="intel_pstate=active"
  elif [ "$driver" = "amd_pstate" ]; then
    # amd_pstate supports active/passive/guided depending on kernel; active is a reasonable default.
    pstate_param="amd_pstate=active"
  fi
fi

# Write base TLP config (safe defaults; adjust values below if you want more aggressive perf)
if [[ "$extra" == "laptop" ]]; then
  cat >/etc/tlp.conf <<EOF
# Generated by installer - baseline TLP config
PLATFORM_PROFILE_ON_AC=performance
PLATFORM_PROFILE_ON_BAT=low-power

# PCIe ASPM: prefer default on AC (don't force performance), aggressive on battery
PCIE_ASPM_ON_AC=default
PCIE_ASPM_ON_BAT=powersupersave

USB_AUTOSUSPEND=1
USB_EXCLUDE_BTUSB=0
USB_EXCLUDE_PHONE=1

# Runtime PM (use new name)
RUNTIME_PM_ON_AC=on
RUNTIME_PM_ON_BAT=auto
RUNTIME_PM_DRIVER_DENYLIST="amdgpu nouveau nvidia"

WIFI_PWR_ON_AC=off
WIFI_PWR_ON_BAT=on

SOUND_POWER_SAVE_ON_AC=0
SOUND_POWER_SAVE_ON_BAT=1

DISK_APM_LEVEL_ON_AC="254 254"
DISK_APM_LEVEL_ON_BAT="128 128"

# Per-disk IO scheduler: use mq-deadline as safe default (leave kernel default with 'keep')
DISK_IOSCHED="mq-deadline"

SATA_LINKPWR_ON_AC=max_performance
SATA_LINKPWR_ON_BAT=min_power

# Charging thresholds (only functional if tlp-rdw and hardware support)
START_CHARGE_THRESH_BAT0=40
STOP_CHARGE_THRESH_BAT0=80
EOF

  # CPU-specific settings by driver
  if [ "$driver" = "intel_pstate" ]; then
    # Use 'active' for AC (intel internal algorithms), use 'passive' on BAT so schedutil can be selected
    cat >>/etc/tlp.conf <<EOF
# Intel pstate tuning
CPU_DRIVER_OPMODE_ON_AC=active
CPU_DRIVER_OPMODE_ON_BAT=passive
CPU_SCALING_GOVERNOR_ON_AC=performance
CPU_SCALING_GOVERNOR_ON_BAT=schedutil
CPU_ENERGY_PERF_POLICY_ON_AC=performance
CPU_ENERGY_PERF_POLICY_ON_BAT=balance_power
CPU_BOOST_ON_AC=1
CPU_BOOST_ON_BAT=0
EOF

  elif [ "$driver" = "amd_pstate" ]; then
    # For AMD: prefer active when the new energy/CPP features exist, otherwise fall back to using schedutil
    if [ -f /sys/devices/system/cpu/cpufreq/policy0/energy_performance_preference ]; then
      cat >>/etc/tlp.conf <<EOF
# AMD pstate with energy perf preference support
CPU_DRIVER_OPMODE_ON_AC=active
CPU_DRIVER_OPMODE_ON_BAT=active
CPU_SCALING_GOVERNOR_ON_AC=performance
CPU_SCALING_GOVERNOR_ON_BAT=powersave
CPU_ENERGY_PERF_POLICY_ON_AC=performance
CPU_ENERGY_PERF_POLICY_ON_BAT=power
CPU_BOOST_ON_AC=1
CPU_BOOST_ON_BAT=0
EOF
    else
      cat >>/etc/tlp.conf <<EOF
# AMD pstate older kernels - keep schedutil
CPU_DRIVER_OPMODE_ON_AC=passive
CPU_DRIVER_OPMODE_ON_BAT=passive
CPU_SCALING_GOVERNOR_ON_AC=schedutil
CPU_SCALING_GOVERNOR_ON_BAT=schedutil
CPU_BOOST_ON_AC=1
CPU_BOOST_ON_BAT=0
EOF
    fi

  else
    # Generic fallback: use schedutil both AC/BAT
    cat >>/etc/tlp.conf <<EOF
# Generic CPUfreq fallback
CPU_DRIVER_OPMODE_ON_AC=passive
CPU_DRIVER_OPMODE_ON_BAT=passive
CPU_SCALING_GOVERNOR_ON_AC=schedutil
CPU_SCALING_GOVERNOR_ON_BAT=schedutil
CPU_BOOST_ON_AC=1
CPU_BOOST_ON_BAT=0
EOF
  fi
fi

# Boot Manager setup
if [[ "$microcode_pkg" == "intel-ucode" ]]; then
  microcode_img="initrd /intel-ucode.img"
elif [[ "$microcode_pkg" == "amd-ucode" ]]; then
  microcode_img="initrd /amd-ucode.img"
fi
mkinitcpio -P
bootctl install
# bootctl update

cat >/boot/loader/loader.conf <<EOF
default arch
timeout 3
editor no
EOF

# common options base
opts_base="root=UUID=$uuid rw zswap.enabled=0 rootfstype=ext4"
if [[ -n "$pstate_param" ]]; then
  opts="$opts_base $pstate_param"
else
  opts="$opts_base"
fi

cat >/boot/loader/entries/arch.conf <<ENTRY
title   Arch Linux
linux   /vmlinuz-linux
$microcode_img
initrd  /initramfs-linux.img
options $opts
ENTRY

if [[ "${howMuch:-}" == "max" ]]; then
  cat >/boot/loader/entries/arch-lts.conf <<ENTRY_LTS
title   Arch Linux (LTS)
linux   /vmlinuz-linux-lts
$microcode_img
initrd  /initramfs-linux-lts.img
options $opts
ENTRY_LTS
fi

# Reflector and pacman Setup
sed -i '/^#Color$/c\Color' /etc/pacman.conf
mkdir -p /etc/xdg/reflector
{
  echo "--save /etc/pacman.d/mirrorlist"
  echo "--protocol https"
  echo "--country India"
  echo "--latest 10"
  echo "--age 24"
  echo "--sort rate"
} >/etc/xdg/reflector/reflector.conf

if [[ "$ddos" == "no" ]]; then
  reflector --country 'India' --latest 10 --age 24 --sort rate --save /etc/pacman.d/mirrorlist
else
  cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.bak
  cat >/etc/pacman.d/mirrorlist <<'EOF'
Server = https://in.arch.niranjan.co/$repo/os/$arch
Server = https://mirrors.saswata.cc/archlinux/$repo/os/$arch
Server = https://mirror.del2.albony.in/archlinux/$repo/os/$arch
Server = https://in-mirror.garudalinux.org/archlinux/$repo/os/$arch
EOF
fi

# Copy config and dotfiles as the user
if [[ "$howMuch" == "max" ]]; then
  su - "$username" -c '
    mkdir -p ~/Documents/projects/default
    # Clone scripts
    git clone https://github.com/zedonix/scripts.git ~/Documents/projects/default/scripts
    git clone https://github.com/zedonix/dotfiles.git ~/Documents/projects/default/dotfiles
    git clone https://github.com/zedonix/archsetup.git ~/Documents/projects/default/archsetup
    git clone https://github.com/zedonix/notes.git ~/Documents/projects/default/notes
    git clone https://github.com/zedonix/GruvboxGtk.git ~/Documents/projects/default/GruvboxGtk
    git clone https://github.com/zedonix/GruvboxQT.git ~/Documents/projects/default/GruvboxQT
  '
  # Root .config
  mkdir -p ~/.config ~/.local/state/bash ~/.local/state/zsh
  echo '[[ -f ~/.bashrc ]] && . ~/.bashrc' >~/.bash_profile
  touch ~/.local/state/zsh/history ~/.local/state/bash/history
  ln -sf /home/$username/Documents/projects/default/dotfiles/.bashrc ~/.bashrc
  ln -sf /home/$username/Documents/projects/default/dotfiles/.zshrc ~/.zshrc
  ln -sf /home/$username/Documents/projects/default/dotfiles/.config/starship.toml ~/.config
  ln -sf /home/$username/Documents/projects/default/dotfiles/.config/nvim/ ~/.config

  # ly config
  # -e 's/^bigclock *= *.*/bigclock = en/' \
  sed -i \
    -e 's/^allow_empty_password *= *.*/allow_empty_password = false/' \
    -e 's/^clear_password *= *.*/clear_password = true/' \
    -e 's/^clock *= *.*/clock = %a %d\/%m %H:%M/' \
    /etc/ly/config.ini

  # Greetd setup for tuigreet
  # cp -f /home/$username/Documents/projects/default/dotfiles/config.toml /etc/greetd/

  # Setup Gruvbox theme
  THEME_SRC="/home/$username/Documents/projects/default/GruvboxQT"
  THEME_DEST="/usr/share/Kvantum/Gruvbox"
  mkdir -p "$THEME_DEST"
  cp "$THEME_SRC/gruvbox-kvantum.kvconfig" "$THEME_DEST/Gruvbox.kvconfig"
  cp "$THEME_SRC/gruvbox-kvantum.svg" "$THEME_DEST/Gruvbox.svg"

  THEME_SRC="/home/$username/Documents/projects/default/GruvboxGtk"
  THEME_DEST="/usr/share"
  cp -r "$THEME_SRC/themes/*" "$THEME_DEST/themes"
  cp -r "$THEME_SRC/icons/*" "$THEME_DEST/icons"

  # Firefox policy
  mkdir -p /etc/firefox/policies
  ln -sf "/home/$username/Documents/projects/default/dotfiles/policies.json" /etc/firefox/policies/policies.json
fi
if [[ "$recovery" == "no" ]]; then
  su - "$username" -c '
  mkdir -p ~/Downloads ~/Desktop ~/Public ~/Templates ~/Videos ~/Pictures/Screenshots/temp ~/.config
  mkdir -p ~/Documents/projects/work ~/Documents/projects/sandbox ~/Documents/personal/wiki
  mkdir -p ~/.local/bin ~/.cache/cargo-target ~/.local/state/bash ~/.local/state/zsh ~/.local/share/wineprefixes
  touch ~/.local/state/bash/history ~/.local/state/zsh/history ~/Documents/personal/wiki/index.txt

  # Copy and link files (only if dotfiles exists)
  if [[ -d ~/Documents/projects/default/dotfiles ]]; then
    cp ~/Documents/projects/default/dotfiles/.config/sway/archLogo.png ~/Pictures/
    cp ~/Documents/projects/default/dotfiles/pics/* ~/Pictures/
    cp -r ~/Documents/projects/default/dotfiles/.local/share/themes/Gruvbox-Dark ~/.local/share/themes/
    ln -sf ~/Documents/projects/default/dotfiles/.bashrc ~/.bashrc
    ln -sf ~/Documents/projects/default/dotfiles/.zshrc ~/.zshrc 

    for link in ~/Documents/projects/default/dotfiles/.config/*; do
      ln -sf "$link" ~/.config/ 
    done
    for link in ~/Documents/projects/default/scripts/bin/*; do
      ln -sf "$link" ~/.local/bin 
    done
  fi

  # Clone tpm
  git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm
  '
  # tldr wiki setup
  curl -L "https://raw.githubusercontent.com/filiparag/wikiman/master/Makefile" -o "wikiman-makefile"
  make -f ./wikiman-makefile source-tldr
  make -f ./wikiman-makefile source-install
  make -f ./wikiman-makefile clean
fi

# Delete variables
shred -u /root/install.conf

# zram config
# Get total memory in MiB
TOTAL_MEM=$(awk '/MemTotal/ {print int($2 / 1024)}' /proc/meminfo)
ZRAM_SIZE=$((TOTAL_MEM / 2))

# Create zram config
mkdir -p /etc/systemd/zram-generator.conf.d
{
  echo "[zram0]"
  echo "zram-size = ${ZRAM_SIZE}"
  echo "compression-algorithm = zstd #lzo-rle"
  echo "swap-priority = 100"
  echo "fs-type = swap"
} >/etc/systemd/zram-generator.conf.d/00-zram.conf

# Services
# rfkill unblock bluetooth
# modprobe btusb || true
if [[ "$howMuch" == "max" ]]; then
  systemctl enable ly cronie sshd reflector.timer
  if [[ "$hardware" == "hardware" ]]; then
    systemctl enable fstrim.timer acpid libvirtd.socket cups ipp-usb docker.socket
  fi
  if [[ "$extra" == "laptop" || "$extra" == "bluetooth" ]]; then
    systemctl enable bluetooth
  fi
  if [[ "$extra" == "laptop" ]]; then
    systemctl enable tlp
  fi
fi
systemctl enable NetworkManager NetworkManager-dispatcher
systemctl mask systemd-rfkill systemd-rfkill.socket
systemctl disable NetworkManager-wait-online.service

# Clean up package cache and Wrapping up
pacman -Scc --noconfirm
